openapi: 3.0.0
info:
  title: Sample API
  description: API description in Markdown.
  version: 1.0.0
servers:
- url: /
paths:
  /:
    get:
      tags:
      - index
      summary: Returns hello world page.
      operationId: rootGET
      responses:
        "200":
          description: OK
      x-swagger-router-controller: Index
  /hash:
    post:
      tags:
      - hash
      summary: Returns hash
      operationId: hashPOST
      responses:
        "200":
          description: Hash object
      x-swagger-router-controller: Hash
  /vhash:
    post:
      tags:
      - vhash
      summary: Returns check status of hash compare
      operationId: vhashPOST
      responses:
        "200":
          description: Hash check status object
      x-swagger-router-controller: Vhash
components: {}
